export const national = [
  {
    name: "西班牙",
    type: "national",
    searchKey: "Spain",
    alias: ["西班牙", "Spain"],
  },
  {
    name: "德国",
    type: "national",
    searchKey: "germany",
    alias: ["德国", "germany"],
  },

  {
    name: "法国",
    type: "national",
    searchKey: "France",
    alias: ["法国", "France"],
  },
  {
    name: "葡萄牙",
    type: "national",
    searchKey: "Portugal",
    alias: ["葡萄牙", "Portugal"],
  },
  {
    name: "荷兰",
    type: "national",
    searchKey: "Netherlands",
    alias: ["荷兰", "Netherlands"],
  },
  {
    name: "比利时",
    type: "national",
    searchKey: "Belgium",
    alias: ["比利时", "Belgium"],
  },
  {
    name: "英格兰",
    type: "national",
    searchKey: "England",
    alias: ["英格兰", "England"],
  },
  {
    name: "意大利",
    type: "national",
    searchKey: "Italy",
    alias: ["意大利", "Italy"],
  },
  {
    name: "土耳其",
    type: "national",
    searchKey: "Turkey",
    alias: ["土耳其", "Turkey"],
  },
  {
    name: "克罗地亚",
    type: "national",
    searchKey: "Croatia",
    alias: ["克罗地亚", "Croatia"],
  },

  {
    name: "苏格兰",
    type: "national",
    searchKey: "Scotland",
    alias: ["苏格兰", "Scotland"],
  },
  {
    name: "阿尔巴尼亚",
    type: "national",
    searchKey: "823619",
    alias: ["阿尔巴尼亚", "Albania"],
  },
  {
    name: "捷克",
    type: "national",
    searchKey: "Czech Republic",
    alias: ["捷克", "Czech Republic"],
  },

  {
    name: "奥地利",
    type: "national",
    searchKey: "Austria",
    alias: ["奥地利", "Austria"],
  },
  {
    name: "匈牙利",
    type: "national",
    searchKey: "Hungary",
    alias: ["匈牙利", "Hungary"],
  },
  // {
  //   name: "塞尔维亚",
  //   type: "national",
  //   searchKey: "1682994",
  //   alias: ["塞尔维亚", "Serbia"],
  // },
  {
    name: "丹麦",
    type: "national",
    searchKey: "Denmark",
    alias: ["丹麦", "Denmark"],
  },
  // {
  //   name: "斯洛文尼亚",
  //   type: "national",
  //   searchKey: "1749062",
  //   alias: ["斯洛文尼亚", "Slovenia"],
  // },
  {
    name: "罗马尼亚",
    type: "national",
    searchKey: "Romania",
    alias: ["罗马尼亚", "Romania"],
  },
  // {
  //   name: "瑞士",
  //   type: "national",
  //   searchKey: "1751960",
  //   alias: ["瑞士", "Switzerland"],
  // },
  // {
  //   name: "斯洛伐克",
  //   type: "national",
  //   searchKey: "1751933",
  //   alias: ["斯洛伐克", "Slovakia"],
  // },
  // {
  //   name: "日本",
  //   type: "national",
  //   searchKey: "Japan",
  //   alias: ["日本", "Japan"],
  // },
  // {
  //   name: "韩国",
  //   type: "national",
  //   searchKey: "Korea",
  //   alias: ["韩国", "Korea"],
  // },
  // {
  //   name: "约旦",
  //   type: "national",
  //   searchKey: "jordan",
  //   alias: ["约旦", "jordan"],
  // },
  // {
  //   name: "卡塔尔",
  //   type: "national",
  //   searchKey: "qatar",
  //   alias: ["卡塔尔", "qatar"],
  // },
]

export const club = [
  {
    name: "巴黎圣日耳曼",
    type: "club",
    searchKey: "paris saint",
    alias: ["巴黎圣日耳曼", "psg"],
  },
  {
    name: "曼城",
    originName: "Manchester City",
    url: "/team/10/manchester-city/",
  },
  { name: "阿森纳", originName: "Arsenal", url: "/team/1/arsenal/" },
  { name: "利物浦", originName: "Liverpool", url: "/team/9/liverpool/" },
  {
    name: "曼联",
    originName: "Manchester United",
    url: "/team/11/manchester-united/",
  },
  {
    name: "热刺",
    originName: "Tottenham Hotspur",
    url: "/team/18/tottenham-hotspur/",
  },
  {
    name: "阿斯顿维拉",
    originName: "Aston Villa",
    url: "/team/2/aston-villa/",
  },
  {
    name: "纽卡斯尔联",
    originName: "Newcastle United",
    url: "/team/13/newcastle-united/",
  },
  { name: "切尔西", originName: "Chelsea", url: "/team/5/chelsea/" },
  {
    name: "西汉姆联",
    originName: "West Ham United",
    url: "/team/19/west-ham-united/",
  },
  {
    name: "诺丁汉森林",
    originName: "Nottingham Forest",
    url: "/team/14/nottingham-forest/",
  },
  {
    name: "布莱顿",
    originName: "Brighton & Hove Albion",
    url: "/team/1808/brighton-hove-albion/",
  },
  { name: "富勒姆", originName: "Fulham", url: "/team/144/fulham/" },
  { name: "埃弗顿", originName: "Everton", url: "/team/7/everton/" },
  {
    name: "水晶宫",
    originName: "Crystal Palace",
    url: "/team/1799/crystal-palace/",
  },
  {
    name: "狼队",
    originName: "Wolverhampton Wanderers",
    url: "/team/110/wolverhampton-wanderers/",
  },
  { name: "布伦特福德", originName: "Brentford", url: "/team/1925/brentford/" },
  { name: "沃特福德", originName: "Watford", url: "/team/1795/watford/" },
  {
    name: "女王公园流浪者",
    originName: "queens-park-rangers",
    url: "/team/15/queens-park-rangers/",
  },
  {
    name: "诺里奇",
    originName: "norwich city",
    url: "/team/1792/norwich-city/",
  },
  {
    name: "伯恩茅斯",
    originName: "AFC Bournemouth",
    url: "/team/1943/afc-bournemouth/",
  },
  { name: "伯恩利", originName: "Burnley", url: "/team/1796/burnley/" },
  {
    name: "谢菲联",
    originName: "Sheffield United",
    url: "/team/1794/sheffield-united/",
  },
  { name: "卢顿", originName: "Luton Town", url: "/team/1923/luton-town/" },
  // 法甲
  {
    name: "巴黎圣日耳曼",
    originName: "Paris Saint Germain",
    url: "/team/73/paris-saint-germain/",
  },
  {
    name: "马赛",
    originName: "Olympique de Marseille",
    url: "/team/219/olympique-de-marseille/",
  },
  { name: "兰斯", originName: "Lens", url: "/team/64/lens/" },
  { name: "摩纳哥", originName: "Monaco", url: "/team/69/monaco/" },
  { name: "里尔", originName: "LOSC Lille", url: "/team/65/losc-lille/" },
  { name: "尼斯", originName: "Nice", url: "/team/72/nice/" },
  { name: "雷恩", originName: "Rennes", url: "/team/74/rennes/" },
  {
    name: "里昂",
    originName: "Olympique Lyonnais",
    url: "/team/66/olympique-lyonnais/",
  },
  { name: "蒙彼利埃", originName: "Montpellier", url: "/team/70/montpellier/" },
  {
    name: "兰斯",
    originName: "Stade de Reims",
    url: "/team/379/stade-de-reims/",
  },
  { name: "南特", originName: "Nantes", url: "/team/71/nantes/" },
  { name: "斯特拉斯堡", originName: "Strasbourg", url: "/team/76/strasbourg/" },
  { name: "布雷斯特", originName: "Brest", url: "/team/378/brest/" },
  { name: "洛里昂", originName: "Lorient", url: "/team/217/lorient/" },
  { name: "图卢兹", originName: "Toulouse", url: "/team/1809/toulouse/" },
  { name: "克莱蒙", originName: "Clermont", url: "/team/1815/clermont/" },
  { name: "梅斯", originName: "Metz", url: "/team/68/metz/" },
  { name: "勒阿弗尔", originName: "Le Havre", url: "/team/1738/le-havre/" },
  // 德甲
  {
    name: "拜仁慕尼黑",
    originName: "FC Bayern München",
    url: "/team/21/fc-bayern-munchen/",
  },
  {
    name: "多特蒙德",
    originName: "Borussia Dortmund",
    url: "/team/22/borussia-dortmund/",
  },
  {
    name: "勒沃库森",
    originName: "Bayer 04 Leverkusen",
    url: "/team/32/bayer-04-leverkusen/",
  },
  {
    name: "rb莱比锡",
    originName: "RB Leipzig",
    url: "/team/112172/rb-leipzig/",
  },
  {
    name: "法兰克福",
    originName: "Eintracht Frankfurt",
    url: "/team/1824/eintracht-frankfurt/",
  },
  {
    name: "沃尔夫斯堡",
    originName: "VfL Wolfsburg",
    url: "/team/175/vfl-wolfsburg/",
  },
  {
    name: "门兴格拉德巴赫",
    originName: "Borussia Mönchengladbach",
    url: "/team/23/borussia-monchengladbach/",
  },
  { name: "弗莱堡", originName: "SC Freiburg", url: "/team/25/sc-freiburg/" },
  {
    name: "柏林联合",
    originName: "FC Union Berlin",
    url: "/team/1831/fc-union-berlin/",
  },
  {
    name: "霍芬海姆",
    originName: "TSG Hoffenheim",
    url: "/team/10029/tsg-hoffenheim/",
  },
  {
    name: "斯图加特",
    originName: "VfB Stuttgart",
    url: "/team/36/vfb-stuttgart/",
  },
  {
    name: "美因茨",
    originName: "FSV Mainz 05",
    url: "/team/169/fsv-mainz-05/",
  },
  {
    name: "不来梅",
    originName: "Werder Bremen",
    url: "/team/38/werder-bremen/",
  },
  {
    name: "奥格斯堡",
    originName: "FC Augsburg",
    url: "/team/100409/fc-augsburg/",
  },
  { name: "科隆", originName: "FC Köln", url: "/team/31/fc-koln/" },
  {
    name: "博鲁姆",
    originName: "VfL Bochum 1848",
    url: "/team/160/vfl-bochum-1848/",
  },
  {
    name: "海德汉姆",
    originName: "Heidenheim",
    url: "/team/111235/heidenheim/",
  },
  {
    name: "达姆施塔特",
    originName: "Darmstadt 98",
    url: "/team/110502/darmstadt-98/",
  },
  // 意甲
  { name: "国际米兰", originName: "Inter", url: "/team/44/inter/" },
  { name: "ac米兰", originName: "Milan", url: "/team/47/milan/" },
  { name: "尤文图斯", originName: "Juventus", url: "/team/45/juventus/" },
  { name: "拉齐奥", originName: "Lazio", url: "/team/46/lazio/" },
  { name: "那不勒斯", originName: "Napoli", url: "/team/48/napoli/" },
  { name: "罗马", originName: "Roma", url: "/team/52/roma/" },
  {
    name: "佛罗伦萨",
    originName: "Fiorentina",
    url: "/team/110374/fiorentina/",
  },
  { name: "亚特兰大", originName: "Atalanta", url: "/team/39/atalanta/" },
  { name: "都灵", originName: "Torino", url: "/team/54/torino/" },
  { name: "萨索洛", originName: "Sassuolo", url: "/team/111974/sassuolo/" },
  { name: "博洛尼亚", originName: "Bologna", url: "/team/189/bologna/" },
  { name: "蒙扎", originName: "Monza", url: "/team/111811/monza/" },
  { name: "乌迪内斯", originName: "Udinese", url: "/team/55/udinese/" },
  {
    name: "萨勒尼塔纳",
    originName: "Salernitana",
    url: "/team/110373/salernitana/",
  },
  {
    name: "维罗纳",
    originName: "Hellas Verona",
    url: "/team/206/hellas-verona/",
  },
  { name: "恩波利", originName: "Empoli", url: "/team/1746/empoli/" },
  { name: "热那亚", originName: "Genoa", url: "/team/110556/genoa/" },
  { name: "卡利亚里", originName: "Cagliari", url: "/team/1842/cagliari/" },
  { name: "莱切", originName: "Lecce", url: "/team/347/lecce/" },
  {
    name: "弗罗西诺内",
    originName: "Frosinone",
    url: "/team/111657/frosinone/",
  },
  // 西甲
  {
    name: "皇家马德里",
    originName: "Real Madrid",
    url: "/team/243/real-madrid/",
  },
  {
    name: "巴塞罗那",
    originName: "FC Barcelona",
    url: "/team/241/fc-barcelona/",
  },
  {
    name: "马德里竞技",
    originName: "Atlético Madrid",
    url: "/team/240/atletico-madrid/",
  },
  {
    name: "毕尔巴鄂竞技",
    originName: "Athletic Club",
    url: "/team/448/athletic-club/",
  },
  {
    name: "皇家贝蒂斯",
    originName: "Real Betis",
    url: "/team/449/real-betis/",
  },
  {
    name: "皇家社会",
    originName: "Real Sociedad",
    url: "/team/457/real-sociedad/",
  },
  { name: "塞维利亚", originName: "Sevilla", url: "/team/481/sevilla/" },
  {
    name: "比利亚雷亚尔",
    originName: "Villarreal",
    url: "/team/483/villarreal/",
  },
  { name: "赫罗纳", originName: "Girona", url: "/team/110062/girona/" },
  { name: "奥萨苏纳", originName: "Osasuna", url: "/team/479/osasuna/" },
  { name: "赫塔菲", originName: "Getafe", url: "/team/1860/getafe/" },
  {
    name: "塞尔塔",
    originName: "Celta de Vigo",
    url: "/team/450/celta-de-vigo/",
  },
  { name: "马略卡", originName: "Mallorca", url: "/team/453/mallorca/" },
  {
    name: "巴列卡诺",
    originName: "Rayo Vallecano",
    url: "/team/480/rayo-vallecano/",
  },
  { name: "阿尔梅里亚", originName: "Almería", url: "/team/1861/almeria/" },
  { name: "卡迪斯", originName: "Cádiz", url: "/team/1968/cadiz/" },
  { name: "巴伦西亚", originName: "Valencia", url: "/team/461/valencia/" },
  {
    name: "拉斯帕尔马斯",
    originName: "Las Palmas",
    url: "/team/472/las-palmas/",
  },
  { name: "格拉纳达", originName: "Granada", url: "/team/110832/granada/" },
  {
    name: "阿拉维斯",
    originName: "Deportivo Alavés",
    url: "/team/463/deportivo-alaves/",
  },
  // 土超
  {
    name: "加拉塔萨雷",
    originName: "Galatasaray",
    url: "/team/325/galatasaray/",
  },
  { name: "费内巴切", originName: "Fenerbahçe", url: "/team/326/fenerbahce/" },
  { name: "贝西克塔斯", originName: "Beşiktaş", url: "/team/327/besiktas/" },
  {
    name: "特拉布宗体育",
    originName: "Trabzonspor",
    url: "/team/436/trabzonspor/",
  },
  {
    name: "阿达纳迪美斯普",
    originName: "Adana Demirspor",
    url: "/team/101016/adana-demirspor/",
  },
  {
    name: "伊斯坦堡普野社希尔",
    originName: "İstanbul Başakşehir",
    url: "/team/101014/istanbul-basaksehir/",
  },
  {
    name: "卡拉古拉克",
    originName: "Fatih Karagümrük",
    url: "/team/111117/fatih-karagumruk/",
  },
  {
    name: "安塔利亚体育",
    originName: "Antalyaspor",
    url: "/team/741/antalyaspor/",
  },
  {
    name: "彭迪克体育",
    originName: "Pendikspor",
    url: "/team/131389/pendikspor/",
  },
  {
    name: "安卡拉古库",
    originName: "Ankaragücü",
    url: "/team/101007/ankaragucu/",
  },
  {
    name: "干亚斯堡",
    originName: "Konyaspor",
    url: "/team/101033/konyaspor/",
  },
  {
    name: "加齐安泰普体育",
    originName: "Gaziantep F.K.",
    url: "/team/110776/gaziantep-fk/",
  },
  { name: "三宗", originName: "Samsunspor", url: "/team/748/samsunspor/" },
  {
    name: "开塞利体育",
    originName: "Kayserispor",
    url: "/team/101020/kayserispor/",
  },
  { name: "里泽斯普尔", originName: "Rizespor", url: "/team/101037/rizespor/" },
  {
    name: "锡瓦斯体育",
    originName: "Sivasspor",
    url: "/team/101041/sivasspor/",
  },
  {
    name: "阿兰亚体育",
    originName: "Alanyaspor",
    url: "/team/113142/alanyaspor/",
  },
  {
    name: "哈塔伊体育",
    originName: "Hatayspor",
    url: "/team/101028/hatayspor/",
  },
  {
    name: "卡斯帕沙体育",
    originName: "Kasımpaşa",
    url: "/team/111339/kasimpasa/",
  },
  {
    name: "伊斯坦布尔体育",
    originName: "İstanbulspor",
    url: "/team/746/istanbulspor/",
  },
  // 荷甲
  { name: "埃因霍温", originName: "PSV", url: "/team/247/psv/" },
  { name: "费耶诺德", originName: "Feyenoord", url: "/team/246/feyenoord/" },
  { name: "阿贾克斯", originName: "Ajax", url: "/team/245/ajax/" },
  {
    name: "艾克马亚",
    originName: "AZ Alkmaar",
    url: "/team/1906/az-alkmaar/",
  },
  { name: "特温特", originName: "FC Twente", url: "/team/1908/fc-twente/" },
  {
    name: "乌得勒支",
    originName: "FC Utrecht",
    url: "/team/1903/fc-utrecht/",
  },
  { name: "尼美根", originName: "NEC", url: "/team/1910/nec/" },
  {
    name: "海伦芬",
    originName: "SC Heerenveen",
    url: "/team/1913/sc-heerenveen/",
  },
  {
    name: "福图纳锡塔德",
    originName: "Fortuna Sittard",
    url: "/team/634/fortuna-sittard/",
  },
  {
    name: "前进之鹰",
    originName: "Go Ahead Eagles",
    url: "/team/100632/go-ahead-eagles/",
  },
  {
    name: "鹿特丹斯巴达",
    originName: "Sparta Rotterdam",
    url: "/team/100646/sparta-rotterdam/",
  },
  { name: "维特斯", originName: "Vitesse", url: "/team/1909/vitesse/" },
  // 苏超
  { name: "凯尔特人", originName: "Celtic", url: "/team/78/celtic/" },
  { name: "流浪者", originName: "Rangers", url: "/team/86/rangers/" },
  { name: "阿伯丁", originName: "Aberdeen", url: "/team/77/aberdeen/" },
  { name: "希伯尼安", originName: "Hibernian", url: "/team/81/hibernian/" },
  { name: "基马诺克", originName: "Kilmarnock", url: "/team/82/kilmarnock/" },
  { name: "利云斯顿", originName: "Livingston", url: "/team/621/livingston/" },
  {
    name: "圣约翰斯通",
    originName: "St. Johnstone",
    url: "/team/100804/st-johnstone/",
  },
  { name: "圣米伦", originName: "St. Mirren", url: "/team/100805/st-mirren/" },
  { name: "罗斯郡", originName: "Ross County", url: "/team/631/ross-county/" },
  { name: "马瑟韦尔", originName: "Motherwell", url: "/team/83/motherwell/" },
  { name: "邓迪联队", originName: "Dundee", url: "/team/180/dundee/" },
  // 葡超
  { name: "本菲卡", originName: "Benfica", url: "/team/234/benfica/" },
  {
    name: "里斯本竞技",
    originName: "Sporting CP",
    url: "/team/237/sporting-cp/",
  },
  { name: "波尔图", originName: "Porto", url: "/team/236/porto/" },
  {
    name: "布拉加",
    originName: "Sporting Braga",
    url: "/team/1896/sporting-braga/",
  },
  { name: "埃斯托里尔", originName: "Estoril", url: "/team/10020/estoril/" },
  {
    name: "吉马良斯",
    originName: "Vitória SC",
    url: "/team/1887/vitoria-sc/",
  },
  { name: "阿洛卡", originName: "Arouca", url: "/team/112513/arouca/" },
  {
    name: "法马利卡奥",
    originName: "Famalicão",
    url: "/team/112809/famalicao/",
  },
  { name: "里奥艾维", originName: "Rio Ave", url: "/team/744/rio-ave/" },
  { name: "查维斯", originName: "Chaves", url: "/team/518/chaves/" },
  {
    name: "波尔蒂莫宁斯",
    originName: "Portimonense",
    url: "/team/10031/portimonense/",
  },
  { name: "卡萨比亚", originName: "Casa Pia", url: "/team/114510/casa-pia/" },
  { name: "博阿维斯塔", originName: "Boavista", url: "/team/1898/boavista/" },
  {
    name: "阿马多拉之星",
    originName: "Estrela Amadora",
    url: "/team/718/estrela-amadora/",
  },
  { name: "法鲁人", originName: "Farense", url: "/team/489/farense/" },
  {
    name: "吉尔维森特",
    originName: "Gil Vicente",
    url: "/team/1888/gil-vicente/",
  },
  { name: "莫雷伦斯", originName: "Moreirense", url: "/team/1900/moreirense/" },
  { name: "维泽拉", originName: "Vizela", url: "/team/111539/vizela/" },
  //
  { name: "利雅得胜利", originName: "Al Nassr", url: "/team/112139/al-nassr/" },
  {
    name: "利雅得新月",
    originName: "Al Shabab",
    url: "/team/111674/al-shabab/",
  },
  {
    name: "伯尔尼年轻人",
    originName: "Young Boys",
    url: "/team/900/young-boys/",
  },
  {
    name: "萨索罗",
    originName: "Sassuolo",
    url: "/team/111974/sassuolo/",
  },
  {
    name: "光州廣",
    originName: "Gwangju",
    url: "/team/112258/gwangju/",
  },
  {
    name: "莫斯科火车头",
    originName: "Lokomotiv Moskva",
    url: "/team/100765/lokomotiv-moskva/",
  },
  {
    name: "伊蒂法克",
    originName: "al ettifaq",
    url: "/team/112096/al-ettifaq/",
  },
  {
    name: "伊斯坦布尔",
    originName: "i̇stanbul başakşehir",
    url: "/team/101014/istanbul-basaksehir/",
  },
]

// const teams: any[] = [
//   "france",
//   "germany",
//   "Netherlands",
//   "brazil",
//   "Belgium",
//   "Argentina",
//   "england",
//   "spain",
//   "portugal",
//   "Mexi",
//   "italy",
//   "states",
//   "wales",
//   "denmark",
//   "poland",
//   "iceland",
//   "canada",
//   "romania",
//   "greece",
//   "ukraine",
//   "sweden",
//   "norway",
//   "china",
//   "czech",
//   "austria",
//   "scotland",
//   "ireland",
//   "hungary",
//   "finland",
//   "northern ireland",
//   "australia",
//   "zealand",
//   "japan",
//   "korea",
//   "Uruguay",
//   "Croatia",
//   "Cameroon",
//   "Ecuador",
//   "Iran",
// ]

// const clubs = [
//   "barcelona",
//   "mancity",
//   "manchester united",
//   "arsenal",
//   "liverpool",
//   "tottenham",
//   "Dortmund",
//   "chelse",
//   "bayern",
//   "real madrid",
//   "germain",
//   "demadrid",
//   "inter",
//   "juventus",
//   "milan",
//   "sevilla",
//   "atalanta",
//   "leicester",
//   "sociedad",
//   "villarreal",
//   "west ham",
//   "leverkusen",
//   "lazio",
//   "roma",
//   "bilbao",
//   "betis",
//   "ajax",
//   "aston",
//   "everton",
//   "lyonnais",
//   "benfica",
//   "porto",
//   "hoffenheim",
//   "wolfsburg",
//   "espanyol",
//   "leeds",
//   "wanderers",
//   "fiorentina",
//   "frankfurt",
//   // "lille",
//   "juniors",
//   "brugge",
//   "udinese",
//   "galatasaray",
//   "fulham",
//   "mallorca",
//   "bordeaux",
//   "celtic",
//   "plate",
//   "napoli",
//   "sampdoria",
//   "leipzig",
//   "nottingham",
//   "psv",
//   "marseille",
//   "schalke",
//   "empoli",
//   "feyenoord",
//   "brentford",
//   "norwich",
//   "watford",
//   "southampton",
//   "sunderland",
//   "freiburg",
//   "monaco",
//   "valencia",
//   "crystal",
//   "rennais",
//   "Flamengo",
//   "olympiacos",
//   "levante",
//   "getafe",
//   "nice",
//   "osasuna",
//   "celta",
//   "mineiro",
//   "torino",
//   "racing",
//   "montpellier",
//   "fenerbahce",
//   "strasbourg",
//   "boca",
//   "sassuolo",
//   "Palmeiras",
//   "bologna",
//   "verona",
//   "sparta",
//   "stuttgart",
//   "augsburg",
//   "elche",
//   "vallecano",
//   "sheffield",
//   "Corinthians",
//   "berlin",
//   "santos",
//   "cagliari",
//   "paulo",
//   "celtic",
//   "angeles",
//   "alkmaar",
//   "brestois",
//   "reims",
//   "bournemouth",
//   "istanbul",
//   "salzburg",
//   "zagreb",
//   "kobenhavn",
//   "bochum",
//   "bielefeld",
//   "venezia",
//   "blackburn",
//   "hamburger",
//   "middlesbrough",
//   "kawasaki",
//   "vissel",
//   "yokohama",
//   "Málaga",
//   "hyundai",
//   "jeonbuk",
//   // zhongchao
//   "shandong",
//   "shanghai",
//   "beijing",
//   "shenhua",
//   "yatai",
//   "shenzhen",
//   "wuhan",
//   "guangzhouCity",
//   "henan",
//   "dalian",
//   "shijiazhuang",
//   "tianjin",
//   "qingdao",
//   "guangzhouFc",
//   "chongqing",
//   "hebei",
//   "wuhansanzhen",
//   "azul",
//   "hilal",
//   "kyiv",
//   "eibar",
//   "genoa",
//   "racingclub",
//   "angerssco",
//   "independiente",
//   "werder",
//   "troyes",
//   "fluminense",
//   "metz",
//   "panathinaikos",
//   "genk",
//   "kaa",
//   "fortaleza",
//   "anderlecht",
//   "antwerp",
//   "girona",
//   "goianiense",
//   "queens",
//   "clermont",
//   "salernitana",
//   "seattle",
//   "lanus",
//   "bromwich",
//   "spezia",
//   "demirspor",
//   "greuther",
//   "lorient",
//   "midtjylland",
//   "atlanta united",
//   "reading",
//   "tenerife",
//   "coventry",
//   "middlesbrough",
//   "stoke",
//   "leganes",
//   "talleres",
//   "estoril",
//   "parma",
//   "fortuna",
//   "millwall",
//   "vitesse",
//   "basel",
//   "benevento",
//   "huddersfield",
//   "swansea",
//   "nurnberg",
//   "monza",
//   "gijon",
//   "palmas",
//   "cartagena",
//   "zaragoza",
//   "huesca",
//   "philadelphia",
//   "karlsruher",
//   "paderborn",
//   "auxerre",
//   "Málaga",
//   "birmingham",
//   "lecce",
//   "heidenheim",
//   "cardiff",
//   "galaxy",
//   "diamonds",
//   "hannover",
//   "ponferradina",
//   "oviedo",
//   "toulouse",
//   "kashima",
//   "cerezo",
//   "hull",
//   "bulls",
//   "jeju",
//   "nagoya",
//   "gamba",
//   "sanfrecce",
//   "groningen",
//   "samsung",
//   "seoul",
//   "lugo",
//   "plymouth",
//   "bolton",
//   "kashiwa",
//   "munchen1860",
//   "charlton",
//   "daegu",
//   "port-vale",
//   "northampton",
//   "doncaster",
//   "accrington",
//   "deportivo",
//   "hertha",
//   "cadiz",
//   "granada",
//   "etienne",
//   "nantes",
// ]
